rvsweb/guia-basica-de-desarrollo-full-stack

- _posts/_Caracteristicas.txt
> 36º - D - Cambiar el titulo un renglon

- .gitignore
Quitamos el molesto archivo cspell.json
¿ Quién puso el archivo cspell.json ?
> Quitar archivo cspell.json

- _posts/2021-11-24-git-merge.md
* Necesita mejorar e imagenes
Git - Merge basico
Git - Merge basico , necesita más contexto
> 37 - C - Añadir el post git merge

- README.md
Arreglar el README
El  README estaba hecho unos zorros.
> 37º D - Arreglar el README

- _posts/2021-11-24-git-working-directory.md
- _posts/2021-11-25-git-index-staging-area.md
- _posts/2021-11-25-git-working-tree.md
- _posts/comandos/2021-11-24-git-commit-branch.md
- _posts/comandos/2021-11-25-git-branch-ampliado.md
- _posts/comandos/2021-11-25-git-init.md
- _posts/comandos/2021-11-26-git-commit.md
- _posts/comandos/2021-11-26-git-merge.md
- _posts/comandos/2021-11-27-git-diff.md
- _posts/comandos/2021-11-27-git-log.md
- _posts/comandos/2021-11-27-git-status.md
> 38 - F - Añadir nuevos archivos y cambios

- _posts/comandos/2021-11-25-git-init.md
- _posts/comandos/2021-11-27-git-mv.md
- _posts/comandos/2021-11-27-git-rm.md
- _posts/comandos/2021-11-27-git-stash.md
> 38 - F - A - Añadir los comandos init mv rm stash

- _posts/2021-11-24-git-trabajar-ramas-distintas.md
> Nuevo Pull Request para añadir cambios al proyecto

- _portfolio/2021-11-25-the_movies_home.md
> 39º - B - Modificar texto

- _posts/2021-11-29-git-terminologia.md
- _posts/comandos/2021-11-27-git-diff.md
- _posts/comandos/2021-11-29-git-add copy.md
- _posts/comandos/2021-11-29-git-add.md
Arreglar contenido 
Arreglar contenido para mejorar el entendimiento de los post.
> 39º - D - Modificar texto

- _posts/2021-11-29-git-terminologia.md
> 39º - I - Agregar post git terminologia

- _posts/comandos/2021-11-27-git-diff.md
- _posts/comandos/2021-11-27-git-status.md
> 41º - Arreglar contenido

- _posts/2021-11-25-git-working-tree.md
- _posts/2021-12-02-git-repositorio-local.md
- _posts/comandos/2021-11-27-git-rm.md
- _posts/comandos/2021-11-27-git-status.md
> 41º - Agregamos cambios a los post creados

- README.md
> 41º - Cambiar categorias

- README.md
> 41º - A - Añadir cambios al README

- README.md
> 41º - D - Subir cambios de README

- README.md
- _posts/2021-12-09-git-tres-arboles.md
> 42º - Añadir ejemplo de tres arboles

- _posts/comandos/2021-11-25-git-init.md
> 42º - Ultimos arreglos

- README.md
- _posts/2021-12-07-git-untracked.md
- _posts/comandos/2021-11-25-git-init.md
- _posts/comandos/2021-11-26-git-commit.md
- _posts/comandos/2021-11-26-git-merge.md
- _posts/comandos/2021-11-27-git-diff.md
- _posts/comandos/2021-11-27-git-log.md
- _posts/comandos/2021-11-27-git-rm.md
- _posts/comandos/2021-11-27-git-status.md
- _posts/comandos/2021-11-29-git-add.md
- _posts/comandos/2021-11-29-git-restore.md
- _posts/comandos/2021-12-1-git-checkout.md
- _posts/comandos/2021-12-1-git-fetch.md
- _posts/comandos/2021-12-1-git-push.md
- _posts/comandos/2021-12-1-git-reset.md
- _posts/comandos/2021-12-14-git-restore-rm.md
- _posts/comandos/2021-12-8-git-clone.md
> 43º - D - Añadir cambios en varios articulos

- _posts/comandos/2021-11-27-git-rm.md
- _posts/linux/2021-11-17-communication.md
> 44º - AÑadir cambios a los articulos de linux y git rm

- .cspell/custom-dictionary.txt
- _config.yml
- _posts/linux/2021-11-16-linux-redireccionar-salida-de-datos.md
- _posts/linux/2021-11-17-linux-gestion-de-archivos.md
- _posts/linux/2021-11-19-linux-tratamiento-de-texto.md
> 45º - A - Añadir cambios en el blog y nuevos post sobre Linux

- .cspell/custom-dictionary.txt
- _posts/linux/2021-11-16-linux-redireccionar-salida-de-datos.md
- _posts/linux/2021-11-17-linux-communication.md
- _posts/linux/2021-11-17-linux-gestion-de-archivos.md
- _posts/linux/2021-11-19-linux-compresion-archivos.md
- _posts/linux/2021-11-19-linux-tratamiento-de-texto.md
- _posts/linux/2021-11-20-linux-status.md
> 45º - B - Añadir ejemplos sobre Linux

- _posts/linux/2021-11-19-linux-compresion-archivos.md
- _posts/linux/2022-01-02-linux-tar.md
> 45º - C - Añadir ejemplos de tar

- .cspell/custom-dictionary.txt
- _posts/linux/2022-01-02-linux-tar.md
- cspell.json
> 46 - Ejemplos de tar

- .cspell/custom-dictionary.txt
- _posts/linux/2022-01-02-linux-tar.md
> 46º - A - Arreglar ejemplos de tar

- .cspell/custom-dictionary.txt
- _posts/linux/2021-11-17-linux-comunicacion.md
- _posts/linux/2021-11-17-linux-sistema.md
- _posts/linux/2021-11-18-linux-buscadores.md
- _posts/linux/2021-11-19-linux-compresion-archivos.md
- _posts/linux/2022-01-02-linux-tar.md
- _posts/linux/2022-01-06-linux-combinaciones-de-teclas.md
- _posts/linux/2022-01-06-linux-directorios.md
- _posts/linux/2022-01-06-linux-instalacion.md
- _posts/linux/2022-01-06-linux-permisos.md
- _posts/linux/2022-01-06-linux-redes.md
> 46º B - Añadir nuevos comandos de Linux y arreglar otros post

- _posts/linux/2022-01-07-linux-conceptos-basicos.md
- _posts/linux/2022-01-12-linux-comandos.md
Mover la imagen del post de comandos
> 47º - D - Arreglar fallos y corregir errores

- .cspell/custom-dictionary.txt
- _posts/linux/2021-11-16-linux-redireccionar-salida-de-datos.md
- _posts/linux/2021-11-17-linux-sistema.md
- _posts/linux/2022-01-12-linux-entrada-stdin.md
- _posts/linux/2022-01-12-linux-salida-stdout.md
- _posts/linux/2022-01-14-linux-variables-shell.md
- _posts/linux/comandos/2022-01-12-linux-comandos.md
- _posts/linux/comandos/2022-01-13-linux-grep.md
- _posts/linux/comandos/2022-01-13-linux-wc.md
Añadir el post variables
Arreglar los post comandos , grep , wc , redireccion , sistemas
Arreglar los post entrada , salida
> 47º - G - Añadir cambios a varios post

- .cspell/custom-dictionary.txt
- _posts/linux/2021-11-17-linux-sistema.md
- _posts/linux/2022-01-07-linux-conceptos-basicos.md
- _posts/linux/2022-01-10-linux-editor-vi.md
- _posts/linux/2022-01-12-linux-salida-stdout.md
- _posts/linux/2022-01-14-linux-variables-shell.md
- _posts/linux/2022-01-15-linux-crear-shell-scripts-basicos.md
- _posts/linux/comandos/2022-01-12-linux-comandos.md
- _posts/linux/comandos/2022-01-13-linux-grep.md
- _posts/linux/comandos/2022-01-13-linux-wc.md
- _posts/linux/comandos/2022-01-15-linux-find.md
- _posts/linux/comandos/2022-01-15-linux-od.md
Agregar nuevo contenido al post shell script basico
Agregar mas contenido al comando find
Agregar mas contenido al comando od
> 47º - H - Añadir mas contenido

- README.md
- _posts/git/git-comandos/2021-11-25-git-init.md
- _posts/git/git-comandos/2021-11-26-git-commit.md
- _posts/linux/comandos/2022-01-12-linux-comandos.md
- _posts/linux/comandos/2022-01-18-linux-tldr.md
Añadir el post del comando TLDR
> 47º - I - Arreglar varios post

- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
Añadir post sobre la creacion de una clave ssh-keygen
Configurar la clave publica RSA generada por ssh-keygen
Mostrar como se sincroniza el Repositorio Local con el Repositorio Remoto
> 47º 2º - L - Añadir nuevos posts

- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
Añadir post sobre la creacion de una clave ssh-keygen
Configurar la clave publica RSA generada por ssh-keygen
Mostrar como se sincroniza el Repositorio Local con el Repositorio Remoto
> 47º 3º - L - Añadir nuevos posts

- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
> 48º - Me dio un error al subir la anterior version

- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
> 48º - A - Cambiamos el formato de las imagenes del Markdown

- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
> 48º - B - Cambiamos el formato de las imagenes del Markdown

- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
> 48º - D - Cambiamos el formato de las imagenes del Markdown

- _config.yml
- _posts/git/git-conceptos/2021-11-29-git-terminologia.md
- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
> 48º - E - Cambiamos el formato de las imagenes del Markdown

- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
> 49º - A - Cambiamos la ruta basicas de las images de los archivos

- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
> 49º - B - Añadimos las imagenes arregladas del post ssh

- _posts/git/git-comandos/2021-12-20-git-remote.md
Añadir post sobre como eliminar el ultimo commit
Como eliminar los cambios y arreglar git remote
Como sacar un archivo del Staging Area y enviarlo al Working Directory
> 49º - D-1 - Cambiar contenido de los post

- _posts/git/git-conceptos/2021-12-15-git-head.md
- _posts/git/git-conceptos/2022-01-25-git-grafo-de-commits.md
> 50 - C - Corregir y arreglar post del grafo

- _posts/git/git-comandos/2021-12-20-git-remote.md
- _posts/git/git-comandos/2022-01-26-git-show.md
> 50º - E - Añadir cambios en los posts

- _posts/git/git-comandos/2021-11-25-git-branch.md
- _posts/git/git-comandos/2021-11-27-git-log.md
- _posts/git/git-comandos/2021-12-1-git-checkout.md
- _posts/git/git-comandos/2021-12-1-git-reset.md
> 50º - F - Añadir nuevos arreglos

- _posts/git/git-comandos/2021-11-24-git-commit.md
- _posts/git/git-comandos/2021-11-27-git-diff.md
- _posts/git/git-comandos/2021-11-27-git-rm.md
- _posts/git/git-comandos/2021-11-27-git-status.md
- _posts/git/git-comandos/2021-11-29-git-add.md
- _posts/git/git-comandos/2021-11-29-git-restore.md
- _posts/git/git-comandos/2021-12-1-git-push.md
- _posts/git/git-comandos/2021-12-20-git-remote.md
- _posts/git/git-conceptos/2021-11-24-git-basico.md
- _posts/git/git-conceptos/2021-11-25-git-index-staging-area.md
- _posts/git/git-conceptos/2021-11-25-git-working-tree.md
- _posts/git/git-conceptos/2021-11-29-git-terminologia.md
- _posts/git/git-conceptos/2021-12-06-git-workflow.md
- _posts/git/git-conceptos/2021-12-07-git-untracked.md
- _posts/git/git-conceptos/2021-12-09-git-tres-arboles.md
- _posts/git/git-conceptos/2021-12-15-git-head.md
- _posts/git/git-conceptos/2021-12-19-git-repositorios.md
- _posts/git/git-conceptos/2022-01-21-git-conectar-repo-local-repo-remoto-ssh.md
- _posts/git/git-conceptos/2022-01-24-git-restaurar-archivo-confirmado.md
> 50º - G - Añadir cambios a las palabras Repo.Remote

- _posts/git/git-comandos/2021-11-26-git-commit.md
- _posts/git/git-comandos/2021-11-27-git-diff.md
- _posts/git/git-comandos/2021-12-1-git-reset.md
- _posts/git/git-comandos/2022-02-15-git-cat-file.md
- _posts/git/git-comandos/2022-02-15-git-ls-files.md
- _posts/git/git-comandos/2022-02-16-git-tag.md
- _posts/git/git-comandos/2022-02-17-git-rebase.md
- _posts/git/git-conceptos/2022-02-11-git-recolector-basura.md
- _posts/git/git-conceptos/2022-02-11-git-unstaged.md
> 50º - K - Añadir cambios

- _posts/git/git-comandos/2022-02-17-git-rebase.md
- _posts/git/git-conceptos/2021-11-29-git-terminologia.md
> 50º - L - Añadir Cambios

- _posts/java/2022-04-09-java-interfaces.md
> 51 - d - Añadir nuevo post java interfaces

- .cspell/custom-dictionary.txt
- _posts/git/git-comandos/2021-11-24-git-commit.md
- _posts/git/git-comandos/2021-12-1-git-fetch.md
- _posts/git/git-comandos/2022-03-01-git-fetch.md
- _posts/java/2022-04-12-java-enumerados.md
- _posts/java/2022-04-17-java-clases.md
- _posts/java/2022-04-17-java-herencia.md
- _posts/java/2022-04-19-java-argumentos.md
- _posts/java/2022-04-19-java-super.md
> 52 - Enum - Herencia - Argumentos - Commit

- _posts/git/git-comandos/2021-11-25-git-branch.md
- _posts/git/git-comandos/2021-11-26-git-commit.md
- _posts/git/git-comandos/2021-11-27-git-diff.md
- _posts/git/git-comandos/2021-11-27-git-status.md
- _posts/git/git-comandos/2021-11-29-git-add.md
- _posts/git/git-comandos/2021-12-1-git-checkout.md
- _posts/git/git-comandos/2021-12-1-git-push.md
- _posts/git/git-comandos/2021-12-20-git-remote.md
- _posts/git/git-comandos/2022-03-02-git-pull.md
- _posts/git/git-comandos/2022-03-15-git-tag.md
- _posts/git/git-comandos/2022-03-16-git-archivo.md
Cambiara Repositorio Remoto a la definición correcta
> 52 - Arreglar post de git

- _config.yml
- _posts/java/abstracción/2022-04-10-java-abstractas.md
- _posts/java/modificadores/2022-05-03-java-modificadores-default.md
- _posts/java/modificadores/2022-05-03-java-modificadores-private.md
- _posts/java/modificadores/2022-05-03-java-modificadores-protected.md
- _posts/java/modificadores/2022-05-03-java-modificadores-public.md
- _posts/java/modificadores/2022-05-04-java-modificadores-final.md
- _posts/java/modificadores/2022-05-04-java-modificadores-static.md
- _posts/java/modificadores/2022-05-05-java-synchronized.md
- _posts/java/package/2022-05-06-package.md
- _posts/java/parametros_arguments/2022-05-05-java-parametros_argumentos.md
Abstracción
Package
Parametros & argumentos
Modificadores private , default , protected , final , static ,public , synchronized
> 52 - B - Añadir ejemplos de :

- _posts/java/api/excepciones/2022-05-18-excepciones-throwable.md
- _posts/java/excepciones/2022-05-03-java-excepciones.md
- _posts/java/excepciones/2022-05-03-java-runtime-exception.md
- _posts/java/linea_de_comandos/2022-05-30-linea-comandos.md
- _posts/java/literal/2022-04-09-java-literales.md
> 52 - F - Añadir ejemplos de excepciones

- _posts/java/tdd/2022-06-17-java-tdd.md
> 52 - H - Añadir Ejemplo de TDD

- _posts/java/tdd/2022-06-17-java-tdd.md
> 52 - H - Añadir Ejemplo de TDD 2º

- _posts/java/interfaces/2022-04-09-java-interfaces.md
- _posts/java/interfaces/2022-06-01-java-interfaces.md
> 52 - I1 - Arreglar concepto de interfaces

- _posts/git/git-comandos/2022-03-16-git-apply.md
- _posts/git/git-comandos/2022-03-16-git-archive.md
- _posts/java/testing_depuracion_logging/2022-04-28-java-logging.md
> 52 - T2 - Arreglar categorias 1

- _posts/git/git-comandos/2022-03-16-git-archive.md
- _posts/java/estructuras_de_datos/core-interfaces/2022-04-14-java-list.md
- _posts/java/estructuras_de_datos/core-interfaces/collections/2022-04-14-java-arraylist.md
- _posts/java/estructuras_de_datos/key_value_collections/2022-04-14-java-hashset.md
- _posts/java/this/2022-04-17-java-this.md
- _posts/java/unboxing/2022-07-03-java-autoboxing-unboxing.md
> 53 - Añadir posts de : Collection

- _posts/java/unboxing/2022-07-03-java-autoboxing-unboxing.md
> 54 - A - Añadir post : Autoboxing Arreglado

- .cspell/custom-dictionary.txt
- _posts/conceptos/2022-07-11-framework.md
- _posts/conceptos/2022-07-11-library_framework.md
> 55 - A2 - Añadir Post Librerias y FrameWork

- _posts/conceptos/2022-07-11-framework.md
> 55 - A3 - Añadir Post Librerias y FrameWork

- _posts/conceptos/2022-07-11-libraries.md
> 55 - A4 - arreglar conceptos de librerias

- _posts/conceptos/2022-07-11-framework.md
- _posts/conceptos/2022-07-11-libraries.md
- _posts/conceptos/2022-07-12-api.md
- _posts/conceptos/2022-07-12-toolkit.md
Arreglar y añadir contenido al framework
Arreglar y añadir contenido a las librerias
Añadir el post de API
Añadir el post del Toolkit
> 55 - A5 - Añadir nuevos Post
